---
# This Playbook will setup maxamillion.so from scratch

# MAKE SURE TO ENABLE PIPELINING IN /etc/ansible/ansible.cfg
# pipelining = True

- hosts: all
  user: root
  roles:
   - role: common
   - role: docker
   - role: keybase
   - role: users
   - role: iptables
   - role: resume
     tags:
       - resume
