---
# pkginstall.yml - install packages
- name: Pre Req Packages
  dnf: pkg={{ item }} state=installed
  with_items:
    - python-keyczar
    - python-simplejson
    - libselinux-python

- name: Install Packages
  dnf: pkg={{ item }} state=installed
  with_items:
    - dnf-plugins-core
    - dnf-plugins-extras-common
    - dnf-plugins-extras-tracer
    - dnf-plugins-extras-repoclosure
    - dnf-plugins-extras-repograph
    - dnf-plugins-extras-kickstart
    - dnf-plugins-extras-show-leaves
    - kernel
    - kernel-doc
    - bash-completion
    - selinux-policy-doc
    - selinux-policy-devel
    - fedora-packager
    - fedora-review
    - fedora-review-tests
    - ltrace
    - strace
    - dstat
    - nmon
    - chrony
    - mutt
    - nmap
    - sysstat
    - vim-enhanced
    - mosh
    - tmux
    - screen
    - git
    - tig
    - rpm-build
    - mock
    - ruby
    - ruby-irb
    - ruby-devel
    - rubygems
    - rubygem-pry
    - man
    - man-pages
    - rsync
    - wget
    - tito
    - rpmdevtools
    - rpmconf
    - rpmdepsize
    - htop
    - powertop
    - iotop
    - fedpkg
    - scl-utils
    - scl-utils-build
    - spec2scl
    - setools-console
    - euca2ools
    - lm_sensors
    - autoconf
    - automake
    - libtool
    - intltool
    - gnupg
    - testdisk
    - tcpdump
    - httpd-tools
    - lsscsi
    - irssi
    - policycoreutils-python
    - setroubleshoot-server
    - ntp
    - ntpdate
    - bind-utils
    - elinks
    - nodejs
    - npm
    - pypy
    - pyrasite
    - Cython
    - python3-Cython
    - python2-devel
    - python3-devel
    - pylint
    - bpython
    - python-pip
    - python-pep8
    - python-epdb
    - python-ipython
    - python-virtualenv
    - python-nose
    - python-demjson
    - python-boto
    - python-nikola
    - python-nikola-doc
    - python-nikola-extras
    - python-passlib
    - python-argcomplete
    - pyside-tools
    - python3
    - python3-bpython
    - python3-pylint
    - python3-pip
    - python3-pep8
    - python3-ipython
    - nmap
    - nmap-ncat
    - asciidoc
    - asciidoc-doc
    - golang
    - cryptsetup
    - goaccess
    - fpaste
    - openscap
    - openscap-scanner
    - openscap-utils
    - openscap-containers
    - openscap-daemon


  tags:
    - pkginstall


# vim:ft=ansible: