---
# selinux.yml - set system wide selinux stuff

- name: Ensure selinux policy installed
  dnf: pkg={{ item }} state=installed
  with_items:
    - selinux-policy
    - selinux-policy-targeted
    - selinux-policy-doc
    - selinux-policy-devel

- name: Enable SELinux - enforcing
  selinux:
    policy: targeted
    state: enforcing


# vim:ft=ansible: