---
# main.yml - configure docker
#

- name: Install docker Packages
  dnf: pkg={{ item }} state=installed
  with_items:
    - docker-io

- name: Start and Enable docker
  service:
    name: docker
    state: started
    enabled: yes


# vim:ft=ansible: